### ISSUE TITLE
Adopt `python -m pip install --upgrade pip` to upgrade pip

### ISSUE THREAD

**Issue by sumedhbala** [udacity/OAuth2.0#16]
Hit this on a Mac running High Sierra, Version .10.13.6 (17G65)
"""
    default:   Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    default: Installing collected packages: pip
    default:   Found existing installation: pip 8.1.1
    default:     Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
    default: Successfully installed pip-18.0
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
    default: Traceback (most recent call last):
    default:   File "/usr/bin/pip", line 9, in <module>
    default:     
    default: from pip import main
    default: ImportError
    default: : 
    default: cannot import name main
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
"""

s/pip install --upgrade pip/python -m pip install --upgrade pip/ in pg_config.sh seems to make it work for me. 
Also Reading posts like https://stackoverflow.com/questions/25749621/whats-the-difference-between-pip-install-and-python-m-pip-install tell you to use `python -m pip` to install/update packages

**Comment by out-running-27** [comment]
Thanks changing:
pip install --upgrade pip -> python -m pip install --upgrade pip
seemed to work for me as well

**Comment by javenschuetz** [comment]
Thanks for posting, it worked.
